# Generated by Django 4.0.6 on 2022-07-22 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='text',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='name',
            field=models.CharField(default='test', max_length=200, verbose_name='Name'),
            preserve_default=False,
        ),
    ]
